openapi: 3.0.0
info:
  title: History Controller
  version: 1.0.0
servers:
  - url: http://localhost:9002
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /histories:
    get:
      tags:
        - default
      summary: GetHistory
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: CreateHistory
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                videoId: 644022ec43b67ff1bac02d61
                type: watch
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
