openapi: 3.0.0
info:
  title: Subscription Controller
  version: 1.0.0
servers:
  - url: http://localhost:9002
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /subscriptions/videos:
    get:
      tags:
        - default
      summary: getSubscribedVideos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /subscriptions/susbcribers:
    get:
      tags:
        - default
      summary: getSubscription
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
